openapi: 3.0.3
info:
  title: Meeting Concluder API
  description: A simple audio recording server using PortAudio and JWT authentication.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /login:
    post:
      summary: Authenticate and receive a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /user:
    get:
      summary: Get user information from the JWT token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  username:
                    type: string
        '401':
          description: Unauthorized
  /start:
    post:
      summary: Start the audio recording
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: clap_detection
          schema:
            type: boolean
            default: true
        - in: query
          name: duration
          schema:
            type: integer
            default: 3600
      responses:
        '200':
          description: Started audio recording
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
  /stop:
    post:
      summary: Stop the audio recording
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Stopped audio recording
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
