package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"

	concluder "github.schibsted.io/alexander-fet-rodseth/hackday-meeting-concluder"
)

const openAIURL = "https://api.openai.com/v1/chat/completions"

type OpenAIRequest struct {
	Model    string        `json:"model"`
	Messages []interface{} `json:"messages"`
}

type OpenAIResponse struct {
	Choices []struct {
		Message struct {
			Role    string `json:"role"`
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

func generateText(prompt string) (string, error) {
	reqBody := OpenAIRequest{
		Model: "gpt-3.5-turbo",
		Messages: []interface{}{
			map[string]string{
				"role":    "user",
				"content": prompt,
			},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", openAIURL, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", concluder.Config.OpenAI_APIKey))

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	responseBody, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	var openAIResp OpenAIResponse

	err = json.Unmarshal(responseBody, &openAIResp)
	if err != nil {
		return "", err
	}

	if len(openAIResp.Choices) == 0 {
		return "", fmt.Errorf("No text generated by the OpenAI API")
	}

	return openAIResp.Choices[0].Message.Content, nil
}

func main() {
	content, err := ioutil.ReadFile("input.txt")
	if err != nil {
		fmt.Printf("Error reading input.txt: %v\n", err)
		return
	}

	transcription := string(content)

	summaryPrompt := fmt.Sprintf("Summarize the following meeting transcription: \"%s\"", transcription)
	summary, err := generateText(summaryPrompt)
	if err != nil {
		fmt.Printf("Error generating summary: %v\n", err)
		return
	}

	conclusionPrompt := fmt.Sprintf("Generate a conclusion for the following meeting transcription: \"%s\"", transcription)
	conclusion, err := generateText(conclusionPrompt)
	if err != nil {
		fmt.Printf("Error generating conclusion: %v\n", err)
		return
	}

	combined := fmt.Sprintf("%s\n\n%s\n", strings.TrimSpace(summary), strings.TrimSpace(conclusion))
	fmt.Print(combined)

	err = ioutil.WriteFile("output.txt", []byte(combined), 0o644)
	if err != nil {
		fmt.Printf("Error writing to output.txt: %v\n", err)
		return
	}
}
