name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y portaudio19-dev ffmpeg
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - name: Install Go dependencies
      run: go get -v ./...
    - name: Build
      run: go build -v
    - name: Test
      run: go test -v
    - name: Build backend
      run: (cd cmd/backend; go build -v)
